SYMBOL_BTC_BUSD = 'BTCBUSD'
SYMBOLS = [SYMBOL_BTC_BUSD]

DURATION_1S = '1s'
DURATION_1M = '1m'
DURATION_5M = '5m'
DURATION_15M = '15m'
DURATION_1H = '1h'
DURATIONS = [DURATION_1S, DURATION_1M, DURATION_5M, DURATION_15M, DURATION_1H]

BUY = 'BUY'
SELL = 'SELL'